version: "3.9"

networks:
  app-net:

volumes:
  db_data:
  minio_data:

services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks: [app-net]

  minio:
    image: minio/minio:latest
    restart: unless-stopped
    env_file: .env
    command: server /data --console-address ":${MINIO_CONSOLE_PORT}"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "${MINIO_PORT}:9000"
      - "${MINIO_CONSOLE_PORT}:${MINIO_CONSOLE_PORT}"
    volumes:
      - minio_data:/data
    networks: [app-net]

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    restart: unless-stopped
    env_file: .env
    command:
      - start-dev
      - --http-port=${KEYCLOAK_PORT}
      - --db=postgres
      - --db-url=jdbc:postgresql://postgres:5432/${KEYCLOAK_DB}
      - --db-username=${POSTGRES_USER}
      - --db-password=${POSTGRES_PASSWORD}
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "${KEYCLOAK_PORT}:${KEYCLOAK_PORT}"
    networks: [app-net]
